FurkanMeclis\GIB\UBL\ApplicationResponse\ApplicationResponse:
    xml_root_name: ApplicationResponse
    xml_root_namespace: 'urn:oasis:names:specification:ubl:schema:xsd:ApplicationResponse-2'
    xml_namespaces:
        '': 'urn:oasis:names:specification:ubl:schema:xsd:ApplicationResponse-2'
        cac: 'urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2'
        cbc: 'urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2'
        ext: 'urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2'