FurkanMeclis\GIB\UBL\ApplicationResponse\ApplicationResponseType:
    properties:
        uBLExtensions:
            expose: true
            access_type: public_method
            serialized_name: UBLExtensions
            xml_element:
                cdata: false
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2'
            accessor:
                getter: getUBLExtensions
                setter: setUBLExtensions
            type: array<FurkanMeclis\GIB\UBL\Common\ExtensionComponents\UBLExtension>
            xml_list:
                inline: false
                entry_name: UBLExtension
                skip_when_empty: true
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2'
        uBLVersionID:
            expose: true
            access_type: public_method
            serialized_name: UBLVersionID
            xml_element:
                cdata: false
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2'
            accessor:
                getter: getUBLVersionID
                setter: setUBLVersionID
            type: FurkanMeclis\GIB\UBL\Common\BasicComponents\UBLVersionID
        customizationID:
            expose: true
            access_type: public_method
            serialized_name: CustomizationID
            xml_element:
                cdata: false
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2'
            accessor:
                getter: getCustomizationID
                setter: setCustomizationID
            type: FurkanMeclis\GIB\UBL\Common\BasicComponents\CustomizationID
        profileID:
            expose: true
            access_type: public_method
            serialized_name: ProfileID
            xml_element:
                cdata: false
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2'
            accessor:
                getter: getProfileID
                setter: setProfileID
            type: FurkanMeclis\GIB\UBL\Common\BasicComponents\ProfileID
        iD:
            expose: true
            access_type: public_method
            serialized_name: ID
            xml_element:
                cdata: false
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2'
            accessor:
                getter: getID
                setter: setID
            type: FurkanMeclis\GIB\UBL\Common\BasicComponents\ID
        uUID:
            expose: true
            access_type: public_method
            serialized_name: UUID
            xml_element:
                cdata: false
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2'
            accessor:
                getter: getUUID
                setter: setUUID
            type: FurkanMeclis\GIB\UBL\Common\BasicComponents\UUID
        issueDate:
            expose: true
            access_type: public_method
            serialized_name: IssueDate
            xml_element:
                cdata: false
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2'
            accessor:
                getter: getIssueDate
                setter: setIssueDate
            type: DateTime
        issueTime:
            expose: true
            access_type: public_method
            serialized_name: IssueTime
            xml_element:
                cdata: false
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2'
            accessor:
                getter: getIssueTime
                setter: setIssueTime
            type: DateTime
        note:
            expose: true
            access_type: public_method
            serialized_name: Note
            xml_element:
                cdata: false
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2'
            accessor:
                getter: getNote
                setter: setNote
            xml_list:
                inline: true
                entry_name: Note
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2'
            type: array<FurkanMeclis\GIB\UBL\Common\BasicComponents\Note>
        signature:
            expose: true
            access_type: public_method
            serialized_name: Signature
            xml_element:
                cdata: false
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2'
            accessor:
                getter: getSignature
                setter: setSignature
            xml_list:
                inline: true
                entry_name: Signature
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2'
            type: array<FurkanMeclis\GIB\UBL\Common\AggregateComponents\Signature>
        senderParty:
            expose: true
            access_type: public_method
            serialized_name: SenderParty
            xml_element:
                cdata: false
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2'
            accessor:
                getter: getSenderParty
                setter: setSenderParty
            type: FurkanMeclis\GIB\UBL\Common\AggregateComponents\SenderParty
        receiverParty:
            expose: true
            access_type: public_method
            serialized_name: ReceiverParty
            xml_element:
                cdata: false
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2'
            accessor:
                getter: getReceiverParty
                setter: setReceiverParty
            type: FurkanMeclis\GIB\UBL\Common\AggregateComponents\ReceiverParty
        documentResponse:
            expose: true
            access_type: public_method
            serialized_name: DocumentResponse
            xml_element:
                cdata: false
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2'
            accessor:
                getter: getDocumentResponse
                setter: setDocumentResponse
            xml_list:
                inline: true
                entry_name: DocumentResponse
                namespace: 'urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2'
            type: array<FurkanMeclis\GIB\UBL\Common\AggregateComponents\DocumentResponse>
